project:
  type: website

website:
  page-navigation: true
  title: "**La Biocolombianita**"
  favicon: logo.png
  page-footer:
    background: "#6297CD"
    foreground: "#FFFFFF"
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Daniela O. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right: 
      - icon: twitter
        href: https://twitter.com/Daniela_Osqui
      - icon: instagram
        href: https://www.instagram.com/labiocolombianita/
      - icon: github
        href: https://github.com/Dani2509
  navbar:
    logo: logo.png
    background: "#FFFFFF"
    foreground: "#0D0D0D"
    
    left:
      - href: index.qmd
        text: "{{< fa house-user >}} Inicio"
      - href: Biologia.qmd
        text: "{{< fa microscope >}} Biología"
      - href: aprendeR.qmd
        text: "{{< fa laptop-code >}} Aprende R"
    right:
      - icon: twitter
        href: https://twitter.com/Daniela_Osqui
      - icon: instagram
        href: https://www.instagram.com/labiocolombianita/
      - icon: github
        href: https://github.com/Dani2509
    cookie-consent: true
format:
  html:
    theme: Lumen
    css: styles.css
    toc: true
    




