project:
  type: website

website:
  page-navigation: true
  title: "**La Biocolombianita**"
  site-url: https://labiocolombianita.netlify.app
  open-graph: true
  favicon: media/logo.ico
  page-footer:
    background: "#f8f9fa"
    foreground: "#212529"
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Daniela O. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right: 
      - icon: twitter
        href: https://twitter.com/Daniela_Osqui
      - icon: instagram
        href: https://www.instagram.com/labiocolombianita/
      - icon: github
        href: https://github.com/Dani2509
  navbar:
    logo: media/logo.ico
    background: "#6297CD"
    foreground: "#FFFFFF"
    
    left:
      - text: Inicio
        href: index.qmd
        icon: house-door
      - text: Biologia
        href: Biologia.qmd
        icon: tree
      - text: Aprende R
        href: aprendeR.qmd
        icon: journal-code
    right:
      - icon: twitter-x
        href: https://twitter.com/Daniela_Osqui
      - icon: instagram
        href: https://www.instagram.com/labiocolombianita/
      - icon: github
        href: https://github.com/Dani2509
    cookie-consent: true
format:
  html:
    theme: 
      - Lumen
      - assets/theme.scss
    toc: true

execute:
  freeze: auto
  warning: false
  message: false
    




